# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1390x774")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=774,
    width=1390,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_rectangle(
    3.0,
    1.0,
    820.0,
    774.0,
    fill="#102542",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    557.0,
    494.0,
    image=image_image_1
)

canvas.create_rectangle(
    3.0,
    760.0,
    1830.0,
    776.6849365234375,
    fill="#F87060",
    outline="")

canvas.create_rectangle(
    814.0,
    1.0,
    1390.0,
    779.0,
    fill="#FFFFFF",  # background
    outline="")

canvas.create_rectangle(
    1033.0,
    106.0,
    1171.0,
    106.0,
    fill="#F87060",  # login line
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1014.0,
    y=652.0,
    width=176.0,
    height=46.20012664794922
)

canvas.create_text(
    380.0,
    717.0,
    anchor="nw",
    text="v1.1",
    fill="#FFFFFF",
    font=("Roboto", 14 * -1)
)

canvas.create_rectangle(
    194.0,
    401.0,
    618.9993286132812,
    401.7469177246094,
    fill="#F87060",  # origin ret - underline
    outline="")

canvas.create_text(
    260.0,
    339.0,
    anchor="nw",
    text="ORIGIN RETRIEVERS",
    fill="#FFFFFF",
    font=("RobotoCondensed Regular", 28 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1102.0,
    238.2493438720703,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#CDD7D6",
    highlightthickness=0
)
entry_1.place(
    x=879.0,
    y=195.0,
    width=446.0,
    height=84.49868774414062
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1102.0,
    402.2493438720703,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#CDD7D6",
    highlightthickness=0
)
entry_2.place(
    x=879.0,
    y=359.0,
    width=446.0,
    height=84.49868774414062
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    1102.0,
    565.2493476867676,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#CDD7D6",
    highlightthickness=0
)
entry_3.place(
    x=879.0,
    y=522.0,
    width=446.0,
    height=84.49869537353516
)

canvas.create_text(
    867.0,
    162.0,
    anchor="nw",
    text="UserName",
    fill="#102542",
    font=("RobotoCondensed Regular", 24 * -1)
)

canvas.create_text(
    867.0,
    330.0,
    anchor="nw",
    text="Password",
    fill="#102542",
    font=("RobotoCondensed Regular", 24 * -1)
)

canvas.create_text(
    1067.0,
    491.0,
    anchor="nw",
    text="Mode",
    fill="#102542",
    font=("RobotoCondensed Regular", 24 * -1)
)

canvas.create_text(
    1050.0,
    61.0,
    anchor="nw",
    text="LOGIN",
    fill="#000000",
    font=("RobotoCondensed Regular", 36 * -1)
)

canvas.create_text(
    70.0,
    621.0,
    anchor="nw",
    text="Images/ videos of individuals, taken with or without consent and often of a sexually-explicit nature, are posted on various social media\n platforms as a tactic of abuse by perpetrators with the intent to harass, impersonate, humiliate and cause harm. Such content has a\n tendency to instantly become viral and causes a lot of distress to the victim. Given a piece of text, image, or video snippet as input, we\n build a solution that can identify the person who was the first one to post it online on a particular social media platform. We give a\n detailed report on how we reached a particular result.\n",
    fill="#FFFFFF",
    font=("RobotoCondensed Regular", 11 * -1)
)
window.resizable(False, False)
window.mainloop()
